import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Link from "next/link";
import { Button, buttonVariants } from "@/components/ui/button";
import { ThemeProvider } from "@/components/ui/themeProvider";
import { ModeToggle } from "@/ModeToggle";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: {
    template: '%s | Gecko',
    default: 'Gecko',
  },
  description: "Generated by create next app",
};

const navItems = [
  { label: 'Home', href: '/' },
  { label: 'About', href: '/about'},
  { label: 'Contact', href: '/contact'},
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={cn(inter.className, "min-h-dvh")}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <header className="container border-b h-16 flex items-center justify-between">
            <h1 className="font-bold">LOGO</h1>
            <ul className="flex gap-4">
              {navItems.map((item, index) => (
                <li key={index}>
                  {/* <Button variant='outline' asChild>
                  <Link href={item.href}>{item.label}</Link>
                </Button> */}
                  <Link
                    className={buttonVariants({ variant: "outline" })}
                    href={item.href}
                  >
                    {item.label}
                  </Link>
                </li>
              ))}
            </ul>
          </header>

          <main>{children}</main>

          <footer className="container sticky top-full h-16 flex justify-between items-center border-t">
            <p>&copy; Gecko</p>

            <ModeToggle />
          </footer>
        </ThemeProvider>
      </body>
    </html>
  );
}
